spring: 
    profiles: 
        active:
        - dev
---
server: 
    port: 7001
spring: 
    profiles: dev           #开发环境
    application: 
        name: microservicecloud-config-client
eureka: 
    instance:
        hostname: eureka7001.com
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl: 
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版
            #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #eureka集群
---
server: 
    port: 7001
spring: 
    profiles: test           #开发环境
    application: 
        name: microservicecloud-config-client
eureka: 
    instance:
        hostname: eureka7001.com
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl: 
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版
  